name: Pull Jateksziget feed

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *" # 6 óránként

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make partners dir
        run: mkdir -p docs/partners

      - name: Download XML
        run: |
          curl -fsSL "https://dl.product-service.dognet.sk/fp/jateksziget.hu-arukereso.xml" -o docs/partners/jateksziget.xml

      - name: Commit if changed
        run: |
          if git diff --quiet -- docs/partners/jateksziget.xml; then
            echo "No changes."
          else
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add docs/partners/jateksziget.xml
            git commit -m "chore(feeds): update jateksziget.xml"
            git push
          fi
